modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "diamondchestshop"
version = "${version}"
displayName = "Diamond Chestshop"
authors = "IAmSneak"
description = '''
Serverside economy mod with diamonds
'''
logoFile = "icon.png"

[[dependencies.diamondchestshop]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.diamondchestshop]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.diamondchestshop]]
modId = "diamondeconomy"
mandatory = true
versionRange = "[1.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.diamondchestshop]]
modId = "cloth_config"
mandatory = true
versionRange = "[6.2.57,)"
ordering = "NONE"
side = "BOTH"